#!/usr/bin/env python3
"""
CLI To-Do App - Generated by Multi-Agent System
This is a basic CLI To-Do app in Python with add, list, and delete features.

The app stores the tasks in a list and allows users to add new tasks, list all tasks, and delete tasks.
"""
import os

# Initialize an empty list to store tasks
tasks = []

def add_task():
    """
    Add a task to the list.

    Asks the user for a task description and adds it to the tasks list.

    :return: None
    """
    task_description = input("Enter a new task: ")
    tasks.append(task_description)
    print(f"Task '{task_description}' added successfully.")

def list_tasks():
    """
    List all tasks in the list.

    If there are no tasks, prints "No tasks available".

    :return: None
    """
    if not tasks:
        print("No tasks available.")
    else:
        print("Tasks:")
        for i, task in enumerate(tasks, 1):
            print(f"{i}. {task}")

def delete_task():
    """
    Delete a task from the list.

    Asks the user for the task number and deletes the corresponding task.

    :return: None
    """
    if not tasks:
        print("No tasks available.")
    else:
        list_tasks()
        task_number = int(input("Enter the task number to delete: "))
        try:
            deleted_task = tasks.pop(task_number - 1)
            print(f"Task '{deleted_task}' deleted successfully.")
        except IndexError:
            print("Invalid task number.")

def main():
    """
    CLI To-Do app main function.

    :return: None
    """
    while True:
        print("\nChoose an option:")
        print("1. Add a task")
        print("2. List tasks")
        print("3. Delete a task")
        print("4. Exit")
        option = input("Enter your choice (1-4): ")
        if option == "1":
            add_task()
        elif option == "2":
            list_tasks()
        elif option == "3":
            delete_task()
        elif option == "4":
            print("Goodbye!")
            break
        else:
            print("Invalid option. Please choose a valid option.")

if __name__ == "__main__":
    main()
